export { default as Svgr } from './svgr'

// Category icons
export { default as CarIcon } from './car.svg'
export { default as BookIcon } from './book.svg'
export { default as PhoneIcon } from './phone.svg'
export { default as VoucherIcon } from './voucher.svg'
export { default as MomBabyIcon } from './mom-baby.svg'
export { default as DailyFoodIcon } from './daily-food.svg'
export { default as ElectronicIcon } from './electronic.svg'
export { default as HomeLivingIcon } from './home-living.svg'
export { default as TechGadgetIcon } from './tech-gadget.svg'
export { default as HealthBeautyIcon } from './health-beauty.svg'
export { default as BasketballIcon } from './basketball.svg'
export { default as HomeApplianceIcon } from './home-appliance.svg'

// Credit card icons
export { default as LeafIcon } from './leaf.svg'
export { default as PlaneIcon } from './plane.svg'
export { default as PayPalIcon } from './paypal.svg'
export { default as CreditCardIcon } from './credit-card.svg'

// Common icons
export { default as ShopperIcon } from './shopper.svg'
export { default as SearchIcon } from './search.svg'
export { default as AlignLeftIcon } from './align-left.svg'
export { default as ArrowLeftIcon } from './arrow-left.svg'
export { default as ArrowRightIcon } from './arrow-right.svg'
export { default as CategoriesIcon } from './categories.svg'
export { default as CartIcon } from './cart.svg'
export { default as ProfileIcon } from './profile.svg'
export { default as MailIcon } from './mail.svg'
export { default as StarIcon } from './star.svg'
export { default as MinusIcon } from './minus.svg'
export { default as PlusIcon } from './plus.svg'
export { default as HeartIcon } from './heart.svg'
export { default as ShieldIcon } from './shield.svg'
export { default as SmileStarIcon } from './smile-star.svg'
export { default as LocationIcon } from './location.svg'
export { default as InfoSquareIcon } from './info-square.svg'
export { default as CallingIcon } from './calling.svg'
export { default as TrashIcon } from './trash.svg'
export { default as PencilLineIcon } from './pencil-line.svg'
export { default as PencilSquareIcon } from './pencil-square.svg'
export { default as PromotionBgSmIcon } from './promotion-bg-sm.svg'
export { default as PromotionBgLgIcon } from './promotion-bg-lg.svg'
export { default as ChevronDownIcon } from './chevron-down.svg'
export { default as FilterIcon } from './filter.svg'
export { default as ShippingTruckIcon } from './shipping-truck.svg'
