name: Deploy Next.js app to production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'npm'
      - name: Create .env file
        run: echo "${{ secrets.ENV }}" > .env
      - run: npm i --force
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/shopper-next
            git fetch --all
            git reset --hard origin/main
            echo "${{ secrets.ENV }}" > .env
            npm i --force
            NODE_OPTIONS="--max-old-space-size=2048" npm run build
            pm2 restart shopper-next
